# Generated by Django 3.1 on 2020-10-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='coast',
            field=models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Custo'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Preço'),
        ),
    ]
