# Generated by Django 3.1 on 2020-10-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_productstock_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='original_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade Original'),
            preserve_default=False,
        ),
    ]
