# Generated by Django 3.1 on 2020-10-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_productstock_original_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='original_quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantidade Original'),
        ),
    ]
