# Generated by Django 3.1 on 2020-10-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20201014_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='original_quantity',
        ),
        migrations.AddField(
            model_name='productstock',
            name='new_quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantidade no estoque'),
        ),
    ]
