# Generated by Django 3.1 on 2020-10-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20201014_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='new_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade no estoque'),
            preserve_default=False,
        ),
    ]
