# Generated by Django 3.1 on 2020-10-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20201014_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='author',
        ),
    ]
