# Generated by Django 3.1 on 2020-10-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_remove_productstock_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='new_quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantidade no estoque'),
        ),
    ]
