# Generated by Django 3.1 on 2020-10-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='author',
        ),
    ]
